### ISSUE TITLE
kittenR()

### ISSUE THREAD

**Issue by anniew** [IndrajeetPatil/kittyR#3]
Ever since I installed it a week ago, kittyR has been sending the loving kitty support I never knew I needed right into my R session :heart_eyes_cat:. It's made work so much more meow-filled and happy than before. 

One thing I've found myself wishing for - :smile_cat: the random selection has only given me one adorable kittenR so far - it's dominated by kittyR (and bigkittyR). I'd like to add a kittenR() function for those days when we just really need a concentrated dose of tiny, tiny kitties.

**Comment by IndrajeetPatil** [comment]
`kittyR` function gains a new argument `only_kitten` to do this. Thanks for the suggestion!

``` r
set.seed(3333)
kittyR::kittyR(meow = FALSE, only_kitten = TRUE)
```

![](https://i.imgur.com/4qvaZQx.png)

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
