### ISSUE TITLE
Error to download kittyR package

### ISSUE THREAD

**Issue by jawadmiyan** [IndrajeetPatil/kittyR#4]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

``` remotes::install_github("IndrajeetPatil/kittyR")
Downloading GitHub repo IndrajeetPatil/kittyR@master

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'dplyr' 0.7.5 is being loaded, but >= 0.8.0 is required
ERROR: lazy loading failed for package 'kittyR'
* removing 'C:/Users/Admin/Documents/R/win-library/j_packages/kittyR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Admin/AppData/Local/Temp/RtmpcNYAeQ/file472c32cd7235/kittyR_0.0.1.tar.gz’ had non-zero exit status

# insert reprex here
```

**Comment by IndrajeetPatil** [comment]
This is the problem:
```r
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'dplyr' 0.7.5 is being loaded, but >= 0.8.0 is required
```

You have `dplyr` version `0.7.5`, but this package needs `0.8.0`. Just update the package version and there shouldn't be any issue.

**Comment by jawadmiyan** [comment]
Thank You... I try to update the dplyr.
