### ISSUE TITLE
Error 403 when accessing URLs

### ISSUE THREAD

**Issue by fernando-kuri** [IndrajeetPatil/kittyR#6]
Hi Indrajeet,

Thank you for this amazing package. I have a problem with a forbidden error (403) and I wanted to verify. 
It goes back to the 'kitty_pics_df' function, more specifically to the rvest::html_session() function. Do you know if I have to make some extra config. or use something like Rselenium?

<img width="776" alt="Screen Shot 2020-01-31 at 23 04 57" src="https://user-images.githubusercontent.com/19256140/73587176-1cebb980-447e-11ea-8093-5b7f6df518c1.png">

Thanks,

```r
> kittyR::kittyR()
Error in read_xml.response(x$response, ..., as_html = as_html) : 
  Forbidden (HTTP 403).
```

**Comment by arunrajes** [comment]
Hi Indrajeet,

I too face the below problem
`> kittyR::kittyR()
Error in read_xml.response(x$response, ..., as_html = as_html) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In request_GET(session, url) : Forbidden (HTTP 403).`

**Comment by IndrajeetPatil** [comment]
Yeah, I can confirm that this package is broken. Both of the sources from which images were being downloaded now require an API. That's going to be a lot more work. I will try to work on it soon, but PRs are of course welcome!

**Comment by arunrajes** [comment]
Hi Indrajeet, I request you to check pupR package. it takes pictures from free-images.com 
I think you can attempt this well. 

Thanks
Arun
